// Code generated by thriftrw-plugin-envelope
// @generated

package plugin

import (
	"github.com/thriftrw/thriftrw-go/internal/envelope"
	"github.com/thriftrw/thriftrw-go/wire"
	"github.com/thriftrw/thriftrw-go/plugin/api"
)

// Client implements a Plugin client.
type client struct {
	client envelope.Client
}

// NewClient builds a new Plugin client.
func NewClient(c envelope.Client) api.Plugin {
	return &client{
		client: c,
	}
}

func (c *client) Goodbye() (err error) {
	args := GoodbyeHelper.Args()

	var body wire.Value
	body, err = args.ToWire()
	if err != nil {
		return
	}

	body, err = c.client.Send("goodbye", body)
	if err != nil {
		return
	}

	var result GoodbyeResult
	if err = result.FromWire(body); err != nil {
		return
	}

	err = GoodbyeHelper.UnwrapResponse(&result)
	return
}

func (c *client) Handshake(
	_Request *api.HandshakeRequest,
) (success *api.HandshakeResponse, err error) {
	args := HandshakeHelper.Args(_Request)

	var body wire.Value
	body, err = args.ToWire()
	if err != nil {
		return
	}

	body, err = c.client.Send("handshake", body)
	if err != nil {
		return
	}

	var result HandshakeResult
	if err = result.FromWire(body); err != nil {
		return
	}

	success, err = HandshakeHelper.UnwrapResponse(&result)
	return
}

// Handler serves an implementation of the Plugin service.
type Handler struct {
	impl api.Plugin
}

// NewHandler builds a new Plugin handler.
func NewHandler(service api.Plugin) Handler {
	return Handler{
		impl: service,
	}
}

// Handle receives and handles a request for the Plugin service.
func (h Handler) Handle(name string, reqValue wire.Value) (wire.Value, error) {
	switch name {

	case "goodbye":
		var args GoodbyeArgs
		if err := args.FromWire(reqValue); err != nil {
			return wire.Value{}, err
		}

		result, err := GoodbyeHelper.WrapResponse(
			h.impl.Goodbye(),
		)
		if err != nil {
			return wire.Value{}, nil
		}

		return result.ToWire()

	case "handshake":
		var args HandshakeArgs
		if err := args.FromWire(reqValue); err != nil {
			return wire.Value{}, err
		}

		result, err := HandshakeHelper.WrapResponse(
			h.impl.Handshake(args.Request),
		)
		if err != nil {
			return wire.Value{}, nil
		}

		return result.ToWire()

	default:

		return wire.Value{}, envelope.ErrUnknownMethod(name)

	}
}
