// Code generated by thriftrw
// @generated

package plugin

import (
	"errors"
	"fmt"
	"github.com/thriftrw/thriftrw-go/plugin/api"
	"github.com/thriftrw/thriftrw-go/wire"
	"strings"
)

type GenerateArgs struct {
	Request *api.GenerateRequest `json:"request,omitempty"`
}

func (v *GenerateArgs) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Request != nil {
		w, err = v.Request.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _GenerateRequest_Read(w wire.Value) (*api.GenerateRequest, error) {
	var v api.GenerateRequest
	err := v.FromWire(w)
	return &v, err
}

func (v *GenerateArgs) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.Request, err = _GenerateRequest_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *GenerateArgs) String() string {
	var fields [1]string
	i := 0
	if v.Request != nil {
		fields[i] = fmt.Sprintf("Request: %v", v.Request)
		i++
	}
	return fmt.Sprintf("GenerateArgs{%v}", strings.Join(fields[:i], ", "))
}

func (v *GenerateArgs) MethodName() string {
	return "generate"
}

func (v *GenerateArgs) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

type GenerateResult struct {
	Success        *api.GenerateResponse `json:"success,omitempty"`
	GeneratorError *api.GeneratorError   `json:"generatorError,omitempty"`
}

func (v *GenerateResult) ToWire() (wire.Value, error) {
	var (
		fields [2]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if v.GeneratorError != nil {
		w, err = v.GeneratorError.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("GenerateResult should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _GenerateResponse_Read(w wire.Value) (*api.GenerateResponse, error) {
	var v api.GenerateResponse
	err := v.FromWire(w)
	return &v, err
}

func _GeneratorError_Read(w wire.Value) (*api.GeneratorError, error) {
	var v api.GeneratorError
	err := v.FromWire(w)
	return &v, err
}

func (v *GenerateResult) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _GenerateResponse_Read(field.Value)
				if err != nil {
					return err
				}
			}
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.GeneratorError, err = _GeneratorError_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if v.GeneratorError != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("GenerateResult should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *GenerateResult) String() string {
	var fields [2]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}
	if v.GeneratorError != nil {
		fields[i] = fmt.Sprintf("GeneratorError: %v", v.GeneratorError)
		i++
	}
	return fmt.Sprintf("GenerateResult{%v}", strings.Join(fields[:i], ", "))
}

func (v *GenerateResult) MethodName() string {
	return "generate"
}

func (v *GenerateResult) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}

var GenerateHelper = struct {
	IsException    func(error) bool
	Args           func(request *api.GenerateRequest) *GenerateArgs
	WrapResponse   func(*api.GenerateResponse, error) (*GenerateResult, error)
	UnwrapResponse func(*GenerateResult) (*api.GenerateResponse, error)
}{}

func init() {
	GenerateHelper.IsException = func(err error) bool {
		switch err.(type) {
		case *api.GeneratorError:
			return true
		default:
			return false
		}
	}
	GenerateHelper.Args = func(request *api.GenerateRequest) *GenerateArgs {
		return &GenerateArgs{Request: request}
	}
	GenerateHelper.WrapResponse = func(success *api.GenerateResponse, err error) (*GenerateResult, error) {
		if err == nil {
			return &GenerateResult{Success: success}, nil
		}
		switch e := err.(type) {
		case *api.GeneratorError:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for GenerateResult.GeneratorError")
			}
			return &GenerateResult{GeneratorError: e}, nil
		}
		return nil, err
	}
	GenerateHelper.UnwrapResponse = func(result *GenerateResult) (success *api.GenerateResponse, err error) {
		if result.GeneratorError != nil {
			err = result.GeneratorError
			return
		}
		if result.Success != nil {
			success = result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}
