// Code generated by thriftrw
// @generated

// Copyright (c) 2016 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package plugin

import (
	"errors"
	"fmt"
	"github.com/thriftrw/thriftrw-go/plugin/api"
	"github.com/thriftrw/thriftrw-go/wire"
	"strings"
)

type HandshakeArgs struct {
	Request *api.HandshakeRequest `json:"request,omitempty"`
}

func (v *HandshakeArgs) ToWire() (wire.Value, error) {
	var (
		fields [1]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Request != nil {
		w, err = v.Request.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _HandshakeRequest_Read(w wire.Value) (*api.HandshakeRequest, error) {
	var v api.HandshakeRequest
	err := v.FromWire(w)
	return &v, err
}

func (v *HandshakeArgs) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.Request, err = _HandshakeRequest_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func (v *HandshakeArgs) String() string {
	var fields [1]string
	i := 0
	if v.Request != nil {
		fields[i] = fmt.Sprintf("Request: %v", v.Request)
		i++
	}
	return fmt.Sprintf("HandshakeArgs{%v}", strings.Join(fields[:i], ", "))
}

func (v *HandshakeArgs) MethodName() string {
	return "handshake"
}

func (v *HandshakeArgs) EnvelopeType() wire.EnvelopeType {
	return wire.Call
}

type HandshakeResult struct {
	Success                 *api.HandshakeResponse       `json:"success,omitempty"`
	UnsupportedVersionError *api.UnsupportedVersionError `json:"unsupportedVersionError,omitempty"`
	HandshakeError          *api.HandshakeError          `json:"handshakeError,omitempty"`
}

func (v *HandshakeResult) ToWire() (wire.Value, error) {
	var (
		fields [3]wire.Field
		i      int = 0
		w      wire.Value
		err    error
	)
	if v.Success != nil {
		w, err = v.Success.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 0, Value: w}
		i++
	}
	if v.UnsupportedVersionError != nil {
		w, err = v.UnsupportedVersionError.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 1, Value: w}
		i++
	}
	if v.HandshakeError != nil {
		w, err = v.HandshakeError.ToWire()
		if err != nil {
			return w, err
		}
		fields[i] = wire.Field{ID: 2, Value: w}
		i++
	}
	if i != 1 {
		return wire.Value{}, fmt.Errorf("HandshakeResult should have exactly one field: got %v fields", i)
	}
	return wire.NewValueStruct(wire.Struct{Fields: fields[:i]}), nil
}

func _HandshakeResponse_Read(w wire.Value) (*api.HandshakeResponse, error) {
	var v api.HandshakeResponse
	err := v.FromWire(w)
	return &v, err
}

func _UnsupportedVersionError_Read(w wire.Value) (*api.UnsupportedVersionError, error) {
	var v api.UnsupportedVersionError
	err := v.FromWire(w)
	return &v, err
}

func _HandshakeError_Read(w wire.Value) (*api.HandshakeError, error) {
	var v api.HandshakeError
	err := v.FromWire(w)
	return &v, err
}

func (v *HandshakeResult) FromWire(w wire.Value) error {
	var err error
	for _, field := range w.GetStruct().Fields {
		switch field.ID {
		case 0:
			if field.Value.Type() == wire.TStruct {
				v.Success, err = _HandshakeResponse_Read(field.Value)
				if err != nil {
					return err
				}
			}
		case 1:
			if field.Value.Type() == wire.TStruct {
				v.UnsupportedVersionError, err = _UnsupportedVersionError_Read(field.Value)
				if err != nil {
					return err
				}
			}
		case 2:
			if field.Value.Type() == wire.TStruct {
				v.HandshakeError, err = _HandshakeError_Read(field.Value)
				if err != nil {
					return err
				}
			}
		}
	}
	count := 0
	if v.Success != nil {
		count++
	}
	if v.UnsupportedVersionError != nil {
		count++
	}
	if v.HandshakeError != nil {
		count++
	}
	if count != 1 {
		return fmt.Errorf("HandshakeResult should have exactly one field: got %v fields", count)
	}
	return nil
}

func (v *HandshakeResult) String() string {
	var fields [3]string
	i := 0
	if v.Success != nil {
		fields[i] = fmt.Sprintf("Success: %v", v.Success)
		i++
	}
	if v.UnsupportedVersionError != nil {
		fields[i] = fmt.Sprintf("UnsupportedVersionError: %v", v.UnsupportedVersionError)
		i++
	}
	if v.HandshakeError != nil {
		fields[i] = fmt.Sprintf("HandshakeError: %v", v.HandshakeError)
		i++
	}
	return fmt.Sprintf("HandshakeResult{%v}", strings.Join(fields[:i], ", "))
}

func (v *HandshakeResult) MethodName() string {
	return "handshake"
}

func (v *HandshakeResult) EnvelopeType() wire.EnvelopeType {
	return wire.Reply
}

var HandshakeHelper = struct {
	IsException    func(error) bool
	Args           func(request *api.HandshakeRequest) *HandshakeArgs
	WrapResponse   func(*api.HandshakeResponse, error) (*HandshakeResult, error)
	UnwrapResponse func(*HandshakeResult) (*api.HandshakeResponse, error)
}{}

func init() {
	HandshakeHelper.IsException = func(err error) bool {
		switch err.(type) {
		case *api.UnsupportedVersionError:
			return true
		case *api.HandshakeError:
			return true
		default:
			return false
		}
	}
	HandshakeHelper.Args = func(request *api.HandshakeRequest) *HandshakeArgs {
		return &HandshakeArgs{Request: request}
	}
	HandshakeHelper.WrapResponse = func(success *api.HandshakeResponse, err error) (*HandshakeResult, error) {
		if err == nil {
			return &HandshakeResult{Success: success}, nil
		}
		switch e := err.(type) {
		case *api.UnsupportedVersionError:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for HandshakeResult.UnsupportedVersionError")
			}
			return &HandshakeResult{UnsupportedVersionError: e}, nil
		case *api.HandshakeError:
			if e == nil {
				return nil, errors.New("WrapResponse received non-nil error type with nil value for HandshakeResult.HandshakeError")
			}
			return &HandshakeResult{HandshakeError: e}, nil
		}
		return nil, err
	}
	HandshakeHelper.UnwrapResponse = func(result *HandshakeResult) (success *api.HandshakeResponse, err error) {
		if result.UnsupportedVersionError != nil {
			err = result.UnsupportedVersionError
			return
		}
		if result.HandshakeError != nil {
			err = result.HandshakeError
			return
		}
		if result.Success != nil {
			success = result.Success
			return
		}
		err = errors.New("expected a non-void result")
		return
	}
}
